### ISSUE TITLE
Connect to a Service without an ELB?

### ISSUE THREAD

**Issue by aphillipo** [brikis98/infrastructure-as-code-talk#10]
Brilliant Example!  

Sorry I'm really new to this stuff so please close if this doesn't quite make sense; I have a load of misc services in my docker-compose file like redis and freegeoip server and I'd like to add them as tasks - how do I connect to them directly without and ELB... Is there a hostname variable I can use for a service?

Thanks again this has really clarified lots of things for me!

EDIT: I just listened to your excellent talk again and sadly you say each service needs an ALB :-/

**Comment by brikis98** [comment]
When using ECS, you have a bunch of EC2 Instances (the "ECS Cluster") and your Docker containers could be scheduled to run on any of those Instances. The Instances themselves have an IP address and hostname you can use to reach the Docker containers running on them, but if that Docker container gets redeployed, it may end up on a different Instance with a different IP.

One way to solve this is with a load balancer like an ELB or ALB. 

If you can't use a load balancer for some reason, you'll need to set up something more complicated, such as service discovery using [Consul](https://www.consul.io/).

**Comment by aphillipo** [comment]
Brilliantly explained!  Thanks for taking the time to help me to understand why you set up terraform this way.
