### ISSUE TITLE
aws_launch_configuration.ecs_instance: missing dependency: data.aws_ami

### ISSUE THREAD

**Issue by acrosson** [brikis98/infrastructure-as-code-talk#7]
I followed the instructions for the terraform-template in the README.

However, I'm getting this error when i run `terraform plan`:
```
Error configuring: 5 error(s) occurred:

* aws_launch_configuration.ecs_instance: missing dependency: data.aws_ami
* aws_iam_role.ecs_instance: missing dependency: data.aws_iam_policy_document
* aws_iam_role_policy.ecs_cluster_permissions: missing dependency: data.aws_iam_policy_document
* aws_iam_role.ecs_service_role: missing dependency: data.aws_iam_policy_document
* aws_iam_role_policy.ecs_service_policy: missing dependency: data.aws_iam_policy_document
```

is there anything else that needs to be done to get this running out of the box?

**Comment by brikis98** [comment]
What version of Terraform are you using?

**Comment by acrosson** [comment]
Terraform v0.6.6

**Comment by brikis98** [comment]
Terraform data sources are only supported in Terraform v0.7.x and up. Please upgrade and try these templates again.

**Comment by acrosson** [comment]
ahh. thats my fault. i installed using brew and my brew wasn't up to date.

Thanks for being so responsive!
