### ISSUE TITLE
Broken link in readme for terraform 

### ISSUE THREAD

**Issue by 17twenty** [brikis98/infrastructure-as-code-talk#8]
The link goes to https://aws.amazon.com/marketplace/ordering?productId=4ce33fd9-63ff-4f35-8d3a-939b641f1931 which is currently 404ing

**Comment by brikis98** [comment]
Where is this link? Which file?

**Comment by 17twenty** [comment]
Terraform-templates/readme.md

**Comment by brikis98** [comment]
Got it. Fixed via https://github.com/brikis98/infrastructure-as-code-talk/commit/49cf80c684ea4d1aca1c97d511ff67bf2ff9d6c9. Thanks!
